### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by davidkpiano** [chielkunkels/react-redux-formal#1]
Hey, would you like to collaborate with me on [React-Redux-Form](https://github.com/davidkpiano/react-redux-form)? Seems like you have a lot of good ideas that we can integrate into the project! 😄

**Comment by chiel** [comment]
Hey there, I haven't really checked that library out, but I can do that in the coming days to see how much we have in common in terms of thoughts!

I'm impressed that you found this library since I've only started publishing it a couple of days ago haha.

What are the main ideas in this library that caught your attention?

**Comment by davidkpiano** [comment]
> I'm impressed that you found this library since I've only started publishing it a couple of days ago haha.

I like keeping track of what's happening in the React/Redux community. :)

> What are the main ideas in this library that caught your attention?

Two things:
- Dynamic forms created from objects (JSON or otherwise) - this has been a huge ask in general in the community and it's definitely possible with React-Redux-Form; it's just a matter of finding a clean API for it.
- A "standard" validation library with configuration and (optional) error messages, such as your `v.required('This field is required')`.

**Comment by chiel** [comment]
> I like keeping track of what's happening in the React/Redux community. :)

Fair enough, was just curious since I didn't publicise it or anything and am only currently using it for my own goals.

> - Dynamic forms created from objects (JSON or otherwise) - this has been a huge ask in general in the community and it's definitely possible with React-Redux-Form; it's just a matter of finding a clean API for it.

This stems mostly from my earlier work on a non-framework form library I made (https://github.com/chielkunkels/informal). That one just built the entire form with very little effort from the developer. The thing that I like about the current `react-redux-formal` approach is that the user can still more or less define the markup themselves since it's just the inputs that get injected.

That said, the inputs do currently get wrapped by some elements. I added a feature today that allows the developer to specify their own inputs though, so you could make it very barebones, or just wrap the fields in additional elements.

> - A "standard" validation library with configuration and (optional) error messages, such as your `v.required('This field is required')`.

The reason I really like handling validators like this, is that it becomes trivial to add validation. All validators are asynchronous on purpose because I feel like "syncronous" validation doesn't really have an edge over asynchronous, plus it allows for easy chaining of validators.

Another thing I really like about the current approach is that each input is separately connected to the store, meaning your form will never have to rerender entirely, it's always just the input.

All in all, I'm pretty happy with the approach I have taken now, I've been experimenting with it for a few weeks, ironing out the details.

Let's see how well this meshes with what you've currently got, and perhaps how many changes would be required to make these things possible. Of course, if the implementation doesn't make sense in the end we can always have multiple libraries in the react community. :)

**Comment by chiel** [comment]
Hi David,

Sorry it took me so long to get back to you - I've been very busy at work and travelled a bit so I have not had too much time on my hands to work on other stuff.

I've taken a look at how your library works as compared to mine, but I think they currently differ a bit too much for a collaboration to make sense. This library will never grow too much from where it is now as I plan to make it very pluggable.

A good example of this is being able to supply your own input types to the library so that you can implement custom field types or modify existing field types.

You are, of course, more than welcome to copy ideas that I've applied to your own library in order to achieve dynamic forms and validation. One thing I would definitely be open to, is to split the validator functions into a separate repository so that they may be shared between our (and perhaps other) libraries.

Thanks again for your interest!

Cheers,
Chiel
